---
title: Data visualization
bibliography: vis.bib
---

<!-- from https://www.w3schools.com/css/css_table.asp -->
<style>
th, td {
   vertical-align: top;
   padding: 15px;
}
tr:nth-child(even) {background-color: #f2f2f2;} 
th {background-color: #ccccff;}
</style>


<!-- COMMENT
	## Current

## Info

-->

### Course meetings

- 16:30-17:20 Mon, 13:30-14:20 Weds, 11:30-12:20 Fri (all Toronto time)
- via [Teams channel](https://teams.microsoft.com/_#/school/conversations/General?threadId=19:WMkvwbwYymVUN2AoIc-v8VrcUAxFa2fADOPK2ftOdKA1@thread.tacv2&ctx=channel) for the first two weeks; thereafter (starting September 20) [BSB 115](https://library.mcmaster.ca/cct/class-dir/bsb-115)
- University policy requires masks in all indoor spaces. 2-meter distancing is officially optional, but we'll do the best we can
- We will record lectures, and will attempt to continue doing so when we move to live lectures
- You are encouraged but not required to keep your cameras on when participating in virtual course activities

### Links

- [Course outline](outline.html) (or at [math & stats web site](https://mcmasteru365.sharepoint.com/:w:/s/sci-course-outlines/EQIfPDteOwhApDyncmtsPccBnD1-BnBNvI3d7lHqbVDRKQ?e=2Vt5pV))
- [Assignments](admin/assignments.html)
- [The github back-end for this site](https://github.com/mac-theobio/DataViz/)
- [Course data directory](data/index.html)
- Topics/tips
   - [strategies for finding help on R stuff](topics/Finding_help.html)
   - [notes on best practices for running R](topics/Running_R.html)
   - [advice for creating reproducible examples](topics/mre.html)
   - [R style guide](topics/R_style.html)
   - [miscellaneous link dump](topics/misc_links.html)
   - [ggplot wish/hack list](topics/ggplot_hacks.md)
   
## Faculty/communication

- [Ben Bolker](http://www.math.mcmaster.ca/~bolker/)
- [Jonathan Dushoff](http://www.biology.mcmaster.ca/dushoff/)
- Best way to reach us is by e-mail to `macdataviz@gmail.com`
- General questions (anything you don't consider private) are best asked in the appropriate channel on Teams

## Schedule

(in development)

```{r setup, echo=FALSE,message=FALSE,warning=FALSE, results="asis", eval=TRUE}
library(huxtable)
library(dplyr)
library(readr)
library(shellpipes)

mk_url <- function(x) {
  ifelse(nchar(trimws(x))==0,x,
         sprintf("[%s](https://mac-theobio.github.io/DataViz/%s.html)",
                 x,x))
}

silent <- (
	tsvRead()
	%>% hux()
	%>% print_html(max_width=1000) 
)

```

## References

